# Generated by Django 4.1.7 on 2023-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTravelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='teamPics')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tourpics',
            name='heading',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
